site_name: Docs | Practicus AI
site_description: Practicus AI developer (SDK), admin, and end user documentation.
site_url: https://docs.practicus.ai
theme:
  name: material
  custom_dir: overrides
  features:
  - content.code.copy
  palette:
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  logo: img/practicus50.png
  favicon: img/practicus50.png
  language: en
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-XHY4LGW10Y
nav:
- Welcome: index.md
- Getting Started: getting-started.md
- Tutorials: tutorials.md
- Technical Tutorial:
  - Getting Started:
    - Introduction: technical-tutorial/getting-started/introduction.md
    - Workers: technical-tutorial/getting-started/workers.md
    - Workspaces: technical-tutorial/getting-started/workspaces.md
    - Add-Ons: technical-tutorial/getting-started/add-ons.md
  - Modeling:
    - Introduction: technical-tutorial/modeling/introduction.md
    - Sample Modeling:
      - Build And Deploy: technical-tutorial/modeling/sample-modeling/build-and-deploy.md
  - Workflows:
    - Introduction: technical-tutorial/workflows/introduction.md
    - Tasks:
      - Task Basics: technical-tutorial/workflows/tasks/task-basics.md
    - Airflow:
      - Deploying On Airflow: technical-tutorial/workflows/airflow/deploying-on-airflow.md
    - AI Studio:
      - Generating Wokflows: technical-tutorial/workflows/AI-Studio/generating-wokflows.md
    - Mlflow:
      - Insurance Mlflow: technical-tutorial/workflows/mlflow/insurance-mlflow.md
  - Generative AI:
    - Introduction: technical-tutorial/generative-ai/introduction.md
    - Apps:
      - Build: technical-tutorial/generative-ai/apps/build.md
    - Model Serving:
      - LLM:
        - Model Serving: technical-tutorial/generative-ai/model-serving/llm/model-serving.md
      - Gateway:
        - Model Gateway: technical-tutorial/generative-ai/model-serving/gateway/model-gateway.md
      - Custom:
        - Models:
          - Build: technical-tutorial/generative-ai/model-serving/custom/models/build.md
        - Embeddings:
          - Build: technical-tutorial/generative-ai/model-serving/custom/embeddings/build.md
        - LangChain:
          - Build: technical-tutorial/generative-ai/model-serving/custom/langchain/build.md
    - LangChain:
      - LangChain Basics: technical-tutorial/generative-ai/langchain/langchain-basics.md
      - Streaming: technical-tutorial/generative-ai/langchain/streaming.md
      - Embeddings: technical-tutorial/generative-ai/langchain/embeddings.md
    - Vector Databases:
      - Qdrant: technical-tutorial/generative-ai/vector-databases/qdrant.md
      - Milvus: technical-tutorial/generative-ai/vector-databases/milvus.md
    - Relational Databases:
      - Build: technical-tutorial/generative-ai/relational-databases/build.md
    - Message Queues:
      - Build: technical-tutorial/generative-ai/message-queues/build.md
    - Agentic AI:
      - Build: technical-tutorial/generative-ai/agentic-ai/build.md
    - Message Queues:
      - Build: technical-tutorial/generative-ai/message-queues/build.md
    - MCP:
      - Build: technical-tutorial/generative-ai/mcp/build.md
    - Agentic AI:
      - Build: technical-tutorial/generative-ai/agentic-ai/build.md
    - MCP:
      - Build: technical-tutorial/generative-ai/mcp/build.md
  - Distributed Computing:
    - Introduction: technical-tutorial/distributed-computing/introduction.md
    - Spark:
      - Interactive:
        - Start Cluster: technical-tutorial/distributed-computing/spark/interactive/start-cluster.md
        - Use Cluster: technical-tutorial/distributed-computing/spark/interactive/use-cluster.md
      - Batch Job:
        - Batch Job: technical-tutorial/distributed-computing/spark/batch-job/batch-job.md
      - Auto Scaled:
        - Interactive:
          - Start Cluster: technical-tutorial/distributed-computing/spark/auto-scaled/interactive/start-cluster.md
          - Use Cluster: technical-tutorial/distributed-computing/spark/auto-scaled/interactive/use-cluster.md
        - Batch:
          - Batch Job: technical-tutorial/distributed-computing/spark/auto-scaled/batch/batch-job.md
    - Dask:
      - Interactive:
        - Start Cluster: technical-tutorial/distributed-computing/dask/interactive/start-cluster.md
        - Use Cluster: technical-tutorial/distributed-computing/dask/interactive/use-cluster.md
      - Batch Job:
        - Batch Job: technical-tutorial/distributed-computing/dask/batch-job/batch-job.md
      - Distributed Training:
        - XGBoost: technical-tutorial/distributed-computing/dask/distributed-training/xgboost.md
    - DeepSpeed:
      - Basics:
        - Intro To DeepSpeed: technical-tutorial/distributed-computing/deepspeed/basics/intro-to-deepspeed.md
      - LLM Fine Tuning:
        - Llms With DeepSpeed: technical-tutorial/distributed-computing/deepspeed/llm-fine-tuning/llms-with-deepspeed.md
    - Ray:
      - Interactive:
        - Start Cluster: technical-tutorial/distributed-computing/ray/interactive/start-cluster.md
        - Use Cluster: technical-tutorial/distributed-computing/ray/interactive/use-cluster.md
      - Batch Job:
        - Batch Job: technical-tutorial/distributed-computing/ray/batch-job/batch-job.md
      - Modin:
        - Start Cluster: technical-tutorial/distributed-computing/ray/modin/start-cluster.md
        - Use Cluster: technical-tutorial/distributed-computing/ray/modin/use-cluster.md
      - Vllm:
        - Start Cluster: technical-tutorial/distributed-computing/ray/vllm/start-cluster.md
        - Use Cluster: technical-tutorial/distributed-computing/ray/vllm/use-cluster.md
    - Custom Adaptor:
      - Start Cluster: technical-tutorial/distributed-computing/custom-adaptor/start-cluster.md
      - Use Cluster: technical-tutorial/distributed-computing/custom-adaptor/use-cluster.md
  - Unified DevOps:
    - Introduction: technical-tutorial/unified-devops/introduction.md
    - Secrets With Vault: technical-tutorial/unified-devops/secrets-with-vault.md
    - Automated Init:
      - Build: technical-tutorial/unified-devops/automated-init/build.md
    - Automated Git Sync: technical-tutorial/unified-devops/automated-git-sync.md
    - Git Integrated CICD: technical-tutorial/unified-devops/git-integrated-cicd.md
    - Build Custom Images: technical-tutorial/unified-devops/build-custom-images.md
    - Notifications: technical-tutorial/unified-devops/notifications.md
  - How To:
    - Automate Notebooks:
      - Executing Notebooks: technical-tutorial/how-to/automate-notebooks/executing-notebooks.md
    - Improve Code Quality:
      - Automated Code Quality: technical-tutorial/how-to/improve-code-quality/automated-code-quality.md
    - Work With Connections: technical-tutorial/how-to/work-with-connections.md
    - Automating Kerberos Ticket Renewal With Cron: technical-tutorial/how-to/automating-kerberos-ticket-renewal-with-cron.md
    - Integrate Git: technical-tutorial/how-to/integrate-git.md
    - Use Security Tokens: technical-tutorial/how-to/use-security-tokens.md
    - Work With Processes: technical-tutorial/how-to/work-with-processes.md
    - Work With Data Catalog: technical-tutorial/how-to/work-with-data-catalog.md
    - Caching Large Model Files: technical-tutorial/how-to/caching-large-model-files.md
    - Use Custom Metrics: technical-tutorial/how-to/use-custom-metrics.md
    - Customize Templates: technical-tutorial/how-to/customize-templates.md
    - Hosting Temporary Apis: technical-tutorial/how-to/hosting-temporary-apis.md
    - Change Vs Code Defaults: technical-tutorial/how-to/change-vs-code-defaults.md
    - Configure Advanced Gpu: technical-tutorial/how-to/configure-advanced-gpu.md
    - Configure Workspaces: technical-tutorial/how-to/configure-workspaces.md
    - Share Workers: technical-tutorial/how-to/share-workers.md
    - View Stats: technical-tutorial/how-to/view-stats.md
    - Create Virtual Envs: technical-tutorial/how-to/create-virtual-envs.md
    - Model Tokens: technical-tutorial/how-to/model-tokens.md
    - Use Polars: technical-tutorial/how-to/use-polars.md
    - Use Graph Databases: technical-tutorial/how-to/use-graph-databases.md
    - Personal Startup Scripts: technical-tutorial/how-to/personal-startup-scripts.md
    - MCP Langgraph: technical-tutorial/how-to/mcp-langgraph.md
  - Extras:
    - Modeling:
      - SparkML:
        - Ice Cream:
          - SparkML Ice Cream: technical-tutorial/extras/modeling/sparkml/ice-cream/sparkml-ice-cream.md
        - Spark With Job:
          - Batch Job: technical-tutorial/extras/modeling/sparkml/spark-with-job/batch-job.md
        - Spark For Ds:
          - Spark Tutorial: technical-tutorial/extras/modeling/sparkml/spark-for-ds/spark-tutorial.md
      - Data Mining:
        - Pattern Mining: technical-tutorial/extras/modeling/data-mining/pattern-mining.md
      - Model Tracking:
        - Experiment Tracking:
          - Experiment Tracking Logging: technical-tutorial/extras/modeling/model-tracking/experiment-tracking/experiment-tracking-logging.md
          - Experiment Tracking Model Training: technical-tutorial/extras/modeling/model-tracking/experiment-tracking/experiment-tracking-model-training.md
        - Model Drift:
          - Model Drift: technical-tutorial/extras/modeling/model-tracking/model-drift/model-drift.md
      - Model Observability:
        - Model Observability: technical-tutorial/extras/modeling/model-observability/model-observability.md
      - XGBoost:
        - XGBoost: technical-tutorial/extras/modeling/xgboost/xgboost.md
      - AutoML: technical-tutorial/extras/modeling/AutoML.md
      - Shap Analysis: technical-tutorial/extras/modeling/shap-analysis.md
      - Zip Unzip:
        - Zip Unzip: technical-tutorial/extras/modeling/zip-unzip/zip-unzip.md
      - Examples:
        - Bank Marketing:
          - Bank Marketing: technical-tutorial/extras/modeling/examples/bank-marketing/bank-marketing.md
    - Workflows:
      - Task Runnner App:
        - Build: technical-tutorial/extras/workflows/task-runnner-app/build.md
      - Task Parameters: technical-tutorial/extras/workflows/task-parameters.md
      - Run Task Safe:
        - Deploy: technical-tutorial/extras/workflows/run-task-safe/deploy.md
      - API Triggers For Airflow: technical-tutorial/extras/workflows/api-triggers-for-airflow.md
    - Generative AI:
      - Vector Visualization:
        - Build: technical-tutorial/extras/generative-ai/vector-visualization/build.md
      - Databases:
        - Using Databases: technical-tutorial/extras/generative-ai/databases/using-databases.md
      - Advanced LangChain:
        - Lang Chain LLM Model: technical-tutorial/extras/generative-ai/advanced-langchain/lang-chain-llm-model.md
      - AI Assistants:
        - AI Assistants: technical-tutorial/extras/generative-ai/ai-assistants/ai-assistants.md
      - LLM Evaluation:
        - Overview: technical-tutorial/extras/generative-ai/llm-evaluation/Overview.md
        - Rogue: technical-tutorial/extras/generative-ai/llm-evaluation/ROGUE.md
        - Bleu: technical-tutorial/extras/generative-ai/llm-evaluation/BLEU.md
        - Bleurt: technical-tutorial/extras/generative-ai/llm-evaluation/BLEURT.md
        - Bertscore: technical-tutorial/extras/generative-ai/llm-evaluation/BERTScore.md
        - Meteor: technical-tutorial/extras/generative-ai/llm-evaluation/METEOR.md
        - Perplexity: technical-tutorial/extras/generative-ai/llm-evaluation/Perplexity.md
      - LLM Apps:
        - API LLM Apphost:
          - Build: technical-tutorial/extras/generative-ai/llm-apps/api-llm-apphost/build.md
        - Sdk LLM Apphost:
          - Non-Stream:
            - Sdk Streamlit Hosting: technical-tutorial/extras/generative-ai/llm-apps/sdk-llm-apphost/non-stream/sdk-streamlit-hosting.md
        - Langflow LLM Apphost:
          - Langflow Streamlit Hosting: technical-tutorial/extras/generative-ai/llm-apps/langflow-llm-apphost/langflow-streamlit-hosting.md
      - Milvus Embedding And LangChain:
        - Milvus Chain: technical-tutorial/extras/generative-ai/milvus-embedding-and-langchain/milvus-chain.md
      - Agentic Use Cases:
        - Product Rec:
          - Build: technical-tutorial/extras/generative-ai/agentic-use-cases/product-rec/build.md
        - Growth Strategist:
          - Build: technical-tutorial/extras/generative-ai/agentic-use-cases/growth-strategist/build.md
        - Retention Strategist:
          - Build: technical-tutorial/extras/generative-ai/agentic-use-cases/retention-strategist/build.md
        - Hr:
          - Build: technical-tutorial/extras/generative-ai/agentic-use-cases/hr/build.md
        - Inventroy:
          - Build: technical-tutorial/extras/generative-ai/agentic-use-cases/inventroy/build.md
      - Langflow Apis:
        - Langflow API: technical-tutorial/extras/generative-ai/langflow-apis/langflow-api.md
      - Examples:
        - Prtchatbot:
          - Prtchatbot: technical-tutorial/extras/generative-ai/examples/prtchatbot/prtchatbot.md
        - Mobile-Banking:
          - Mobile-Banking: technical-tutorial/extras/generative-ai/examples/mobile-banking/mobile-banking.md
        - Ecomm-Sdk:
          - Memory Chabot: technical-tutorial/extras/generative-ai/examples/ecomm-sdk/memory-chabot.md
        - Cv Assistant:
          - Cv Assistant: technical-tutorial/extras/generative-ai/examples/cv-assistant/cv-assistant.md
        - Email E Assistant:
          - Mail E-Assistant: technical-tutorial/extras/generative-ai/examples/email-e-assistant/mail-e-assistant.md
        - Memory-Chatbot-Sdk:
          - Chatbot-Console-OpenAI: technical-tutorial/extras/generative-ai/examples/memory-chatbot-sdk/chatbot-console-openai.md
          - Stream Chatbot:
            - Memory Chabot: technical-tutorial/extras/generative-ai/examples/memory-chatbot-sdk/stream-chatbot/memory-chabot.md
      - Deploying LLM:
        - Introduction: technical-tutorial/extras/generative-ai/deploying-llm/Introduction.md
        - Preparation:
          - Model Download: technical-tutorial/extras/generative-ai/deploying-llm/Preparation/Model-Download.md
          - Upload LLM: technical-tutorial/extras/generative-ai/deploying-llm/Preparation/Upload-LLM.md
        - Basic Deployment:
          - Model: technical-tutorial/extras/generative-ai/deploying-llm/basic-deployment/model.md
          - Model Json: technical-tutorial/extras/generative-ai/deploying-llm/basic-deployment/model-json.md
          - Deploy: technical-tutorial/extras/generative-ai/deploying-llm/basic-deployment/deploy.md
          - Consume Parallel: technical-tutorial/extras/generative-ai/deploying-llm/basic-deployment/consume-parallel.md
        - LangChain Deployment:
          - Model: technical-tutorial/extras/generative-ai/deploying-llm/langchain-deployment/model.md
          - Model Json: technical-tutorial/extras/generative-ai/deploying-llm/langchain-deployment/model-json.md
          - Deploy: technical-tutorial/extras/generative-ai/deploying-llm/langchain-deployment/deploy.md
          - Consume Parallel: technical-tutorial/extras/generative-ai/deploying-llm/langchain-deployment/consume-parallel.md
        - Combined Method:
          - Model: technical-tutorial/extras/generative-ai/deploying-llm/combined-method/model.md
          - Model Json: technical-tutorial/extras/generative-ai/deploying-llm/combined-method/model-json.md
          - Deploy: technical-tutorial/extras/generative-ai/deploying-llm/combined-method/deploy.md
          - Consume Parallel: technical-tutorial/extras/generative-ai/deploying-llm/combined-method/consume-parallel.md
    - Data Analysis:
      - Plot:
        - Introduction: technical-tutorial/extras/data-analysis/plot/introduction.md
        - Multiple Layers: technical-tutorial/extras/data-analysis/plot/multiple-layers.md
      - Eda:
        - Analyze: technical-tutorial/extras/data-analysis/eda/analyze.md
    - Data Processing:
      - Pre Process Data:
        - Preprocess: technical-tutorial/extras/data-processing/pre-process-data/preprocess.md
      - Process Data:
        - Insurance: technical-tutorial/extras/data-processing/process-data/insurance.md
        - Insurance With Remote Worker: technical-tutorial/extras/data-processing/process-data/insurance-with-remote-worker.md
        - Spark Custom Config: technical-tutorial/extras/data-processing/process-data/spark-custom-config.md
        - Spark Object Storage: technical-tutorial/extras/data-processing/process-data/spark-object-storage.md
    - Big Data Analytics:
      - Trino:
        - Trino Iceberg API Integration: technical-tutorial/extras/big-data-analytics/trino/trino-iceberg-API-integration.md
- AI Studio Tutorial:
  - Getting Started: ai-studio-tutorial/start.md
  - Intro to Data Analysis: ai-studio-tutorial/data-analysis-intro.md
  - Intro to Plot: ai-studio-tutorial/plot.md
  - Intro to Data Preparation: ai-studio-tutorial/data-prep-intro.md
  - Snippets: ai-studio-tutorial/snippets.md
  - Intro to Workflow Services: ai-studio-tutorial/Workflow.md
  - Intro to Cloud Workers: ai-studio-tutorial/worker-node-intro.md
  - Explore Cloud Data Sources: ai-studio-tutorial/explore.md
  - Data Profiling: ai-studio-tutorial/data-profiling.md
  - Modeling with AutoML: ai-studio-tutorial/model.md
  - Models and Experiments: ai-studio-tutorial/Experiment-Service.md
  - Making Predictions: ai-studio-tutorial/predict.md
  - Working with SQL: ai-studio-tutorial/sql.md
  - Analyzing and preparing data with GPT: ai-studio-tutorial/chatgpt.md
  - Custom ML Models: ai-studio-tutorial/develop_ml_models.md
  - Next Steps: ai-studio-tutorial/next-steps.md
- Operations Tutorial:
  - Getting started: ops-tutorial/start.md
  - Users and Groups: ops-tutorial/create-user-group.md
  - Custom Images: ops-tutorial/custom-images.md
  - Resources Management: ops-tutorial/resources-management.md
  - Storage: ops-tutorial/storage.md
  - Model Deployment: ops-tutorial/model-deployment.md
  - Application Deployment: ops-tutorial/app-deployment.md
  - Git Configuration: ops-tutorial/git-config.md
  - Object Storage: ops-tutorial/object-storage.md
  - Add-on Services: ops-tutorial/add-on-services.md
  - Enterprise SSO: ops-tutorial/enterprise-sso.md
  - AI Assistants: ops-tutorial/ai_assistants.md
  - MFA (Multi-Factor Authentication): ops-tutorial/mfa.md
- SDK v25.5.4: sdk/practicuscore.html
- Legacy:
  - Setup Guide: setup-guide.md
  - Open MLOps:
    - Home: mlops.md
    - For developers: model-api.md
  - Open DataOps:
    - Modern Data Pipelines: modern-data-pipelines.md
    - Code Export: code-export.md
    - Airflow integration: airflow.md
  - Explore: explore.md
  - Cloud: cloud.md
  - Analyze: analyze.md
  - Model: model.md
  - Prepare:
    - Prepare with App: prepare.md
    - Prepare with Excel: excel-prep.md
    - Join: join.md
  - Predict:
    - Predict with App: predict.md
    - Predict with Excel: excel-predict.md
  - AWS IAM policies: aws-iam.md
  - Logging: logging.md
  - Spreadsheets SDK:
    - Home: sdk-start.md
    - Data Preparation use case: data-prep.md
    - Sharing AI Models use case: share-models.md
    - API Reference: api-reference.md
    - Advanced Features: advanced.md
  - Demo Videos: https://practicus.ai/demo
  - Feedback: feedback.md
